# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JJSportSB' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JJSportSB

pod ‘Masonry’
pod ‘YYModel’
pod ‘SDWebImage’
pod 'AMap3DMap', '~> 4.1.0'

end
